global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["host.docker.internal:9090"]
  - job_name: "apps"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          [
            "host.docker.internal:9000",
            "host.docker.internal:9001",
            "host.docker.internal:9002",
            "host.docker.internal:9003",
            "host.docker.internal:9004",
            "host.docker.internal:9005",
            "host.docker.internal:9006",
            "host.docker.internal:9010"
          ]
