apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-service-deploy
  labels:
    app: stock-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-service
  template:
    metadata:
      labels:
        app: stock-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9002"
        prometheus.io/path: /actuator/prometheus
    spec:
      containers:
      - name: stock-service
        image: stock-service:1.0.0
        imagePullPolicy: IfNotPresent
        env:
        - name: logging.config
          value: ""
        - name: management.zipkin.tracing.endpoint
          value: "http://tempo:9411/api/v2/spans"
        ports:
        - containerPort: 9002

---
apiVersion: v1
kind: Service
metadata:
  name: stock-service-svc
  labels:
    app: stock-service
spec:
  selector:
    app: stock-service
  ports:
  - protocol: TCP
    port: 9002
    targetPort: 9002
  type: LoadBalancer
