server.port: 9010

spring:
  application:
    name: messaging
  cloud:
    stream:
      bindings:
        orderProcessConsumer-in-0:
          destination: order-process
          group: order-process-consumer
    function:
      definition: orderProcessConsumer
  rabbitmq:
    host: 127.0.0.1

store:
  messaging:
    destinations:
      order-process:
        - http://localhost:9004/order #payment-service.order
        - http://localhost:9006 #delivery-service

management:
  endpoints.web.exposure.include: "*"
  tracing.sampling.probability: 1.0
  metrics.distribution.percentiles-histogram:
   http.server.requests: true

logging.pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
logging:
  config: classpath:logback-loki.xml
